---
title: "Introduction to Statistical Concepts, MSCA 31000, Assignment 4"
author: "Hope Foster-Reyes"
date: "March 26, 2016"
output: pdf_document
header-includes: \usepackage{amsmath}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Chapter 14, Q2.



## Prepare Environment

Load libraries.

```{r libraries}
library(xlsx)
library(MKmisc)
```

Download data from online Url to subdirectory local to this RStudio project.

```{r download-data}
if (!file.exists("data")) {
  dir.create("data")
}

# !!!This version of file via automated download fails. 
# Remainder of code for assigment assumes manually imported version of .xlsx file located 
# in data subdirectory of working (.rproj) directory
am.url <- "http://onlinestatbook.com/2/case_studies/data/angry_moods.xls"
am.file <- "./data/angry_moods.xls"
if (!file.exists(am.file)) {
  download.file(am.url, destfile = am.file)
}
```

Import data.

```{r import-data}
am.df <- read.xlsx(am.file, 
                   sheetName = "angry_moods.txt", 
                   header = TRUE,
                   colClasses = rep("integer", 7))
```






