---
title: "Introduction to Statistical Concepts, MSCA 31000, Chapter 15 Study Examples"
author: "Hope Foster-Reyes"
date: "April 1, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Chapter 14, Q6.

### Prepare Environment

Load libraries.

```{r libraries}
library(xlsx)
```

Download data from online Url to subdirectory local to this RStudio project.

```{r download-data}
if (!file.exists("data")) {
  dir.create("data")
}

# !!!This version of file via automated download fails. 
# Remainder of code for assigment assumes manually imported version of .xlsx file located 
# in data subdirectory of working (.rproj) directory
am.url <- "http://onlinestatbook.com/2/case_studies/data/angry_moods.xls"
am.file <- "./data/leniency.xls"
if (!file.exists(am.file)) {
  download.file(am.url, destfile = am.file)
}
```

Import data.

```{r import-data}
sl.raw <- read.xlsx(am.file, sheetName = "Sheet1", header = TRUE)
```

### Plot data

```{r plot}
list.plot <- list(
  False = sl.raw$leniency[sl.raw$smile == 1], 
  Felt = sl.raw$leniency[sl.raw$smile == 2],
  Miseraable = sl.raw$leniency[sl.raw$smile == 3],
  Neutral = sl.raw$leniency[sl.raw$smile == 4])
boxplot(list.plot, main = "Smiles and Leniency, Type 7")
```

### Null hypothesis

### Test

```{r compute}
fs.size <- nrow(sl.raw)
fs.group.size <- sum(sl.raw$smile == 1)

fs.mean <- mean(sl.raw$leniency[sl.raw$smile == 1])
fs.var <- var(sl.raw$leniency[sl.raw$smile == 1])
fl.mean <- mean(sl.raw$leniency[sl.raw$smile == 2])
fl.var <- var(sl.raw$leniency[sl.raw$smile == 2])
m.mean <- mean(sl.raw$leniency[sl.raw$smile == 3])
m.var <- var(sl.raw$leniency[sl.raw$smile == 3])
n.mean <- mean(sl.raw$leniency[sl.raw$smile == 4])
n.var <- var(sl.raw$leniency[sl.raw$smile == 4])

MSE <- mean(c(fs.var, fl.var, m.var, n.var))
MSB <- fs.group.size * var(c(fs.mean, fl.mean, m.mean, n.mean))
```

